placeholders:
    view_content_data_additional_information:
        items:
            oro_issue.datagrid.on_user_page: ~

items:
    oro_issue.datagrid.on_user_page:
        template: OroIssueBundle:Issue:issueUser.html.twig
        applicable: "@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)"

    oro_issue.add.button:
        template: OroIssueBundle:Issue:addIssueButton.html.twig


    oro_issue.create.on_user_page.button:
        template: OroIssueBundle:Issue:addIssueButton.html.twig
        applicable: "@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)"

    oro_issue.create.on_user_page.link:
        template: OroIssueBundle:Issue:addIssueLink.html.twig
        applicable: "@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)"