workflows:
    oro_issue_flow:
        label: 'Issue Flow'
        entity: Oro\Bundle\IssueBundle\Entity\Issue
        entity_attribute: issue
        start_step: open

        steps:
            open:
                label: 'Open'
                order: 10
                allowed_transitions:
                    - start_progress
                    - resolve
                    - close
            in_progress:
                label: 'In progress'
                order: 20
                allowed_transitions:
                    - stop_progress
                    - resolve
                    - close
            resolved:
                label: 'Resolved'
                order: 30
                allowed_transitions:
                    - close
                    - reopen
            closed:
                label: 'Closed'
                order: 40
                allowed_transitions:
                    - reopen

        attributes: ~

        transitions:
            start_progress:
                label: 'Start progress'
                is_start: true
                step_to: in_progress
                frontend_options:
                    icon: 'icon-play'
                transition_definition: start_progress_definition

            stop_progress:
                label: 'Stop progress'
                step_to: open
                frontend_options:
                    icon: 'icon-stop'
                transition_definition: stop_progress_definition

            resolve:
                label: 'Resolve'
                step_to: resolved
                frontend_options:
                    icon: 'icon-move'
                transition_definition: resolve_definition

            close:
                label: 'Close'
                step_to: closed
                frontend_options:
                    icon: 'icon-folder-close'
                transition_definition: closed_definition

            reopen:
                label: 'Reopen'
                step_to: open
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'icon-edit'
                transition_definition: reopen_definition

        transition_definitions:
            start_progress_definition: ~
            stop_progress_definition: ~
            closed_definition: ~
            reopen_definition: ~
            resolve_definition: ~